Catalyst set up middleware article
ordercloud-api/oc-documentation pull request #270
Opened 2021-03-10 22:52 UTC by oliverheywood451

2021-03-10 23:01 UTC, robertsoniv requested changes
See review comments for requested changes

2021-03-10 23:01 UTC, robertsoniv commented on content/documents/api-from-scratch.mdx
> +title:          Start .NET middleware from Scratch
Rename your file to match the title as much as possible... something like:
`start-dotnet-middleware-from-scratch.mdx`

2021-03-10 23:01 UTC, robertsoniv commented on content/documents/api-from-scratch.mdx
> +![Alt text](./where_is_your_code.png "New Azure devops Pipeline")
Again, do not store image files in `/content/documents`

2021-03-10 23:03 UTC, robertsoniv commented on content/documents/api-from-scratch.mdx
> +tags:           ["Middleware", "Catalyst", ".NET"]
Consider adding the tag "Integrations"

2021-03-11 16:00 UTC, oliverheywood451 commented
Updated PR based on comments

2021-03-11 16:34 UTC, robertsoniv approved these changes
Awesome! Thanks Oliver

2021-03-11 16:34 UTC, merged