Add more detail on behavior of order return integration event
ordercloud-api/oc-documentation pull request #500
Opened 2022-11-16 15:53 UTC by crhistianramirez

2023-02-08 21:45 UTC, robertsoniv requested changes
@crhistianramirez is this still valid? Sorry haven't gone through PRs in a hot minute. If so, can you resolve the conflicts? If not, close it.

2023-02-08 21:50 UTC, robertsoniv approved these changes

2023-02-08 22:02 UTC, crhistianramirez commented
Yes this is still valid

2023-02-21 22:14 UTC, robertsoniv approved these changes

2023-02-21 22:14 UTC, merged